// Downloads the official Comprehensive Irrigation logo at build time, generates
// favicon sizes from it, and samples the badge's green to use as the brand colour.
//
// Never fails the build: if the logo can't be reached, the brand colour falls
// back to a working estimate and next.config.ts proxies the logo at runtime.

import { mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";

const LOGO_URL = "https://comprehensiveirrigation.com/wp-content/uploads/2023/12/logo.png";
const FALLBACK_GREEN = "#2F5233";

const root = process.cwd();
const brandDir = path.join(root, "public", "brand");
const cssOut = path.join(root, "app", "brand-color.generated.css");

async function writeBrandCss(hex, source) {
  const css = `/* Generated by scripts/fetch-logo.mjs (${source}). Do not edit. */\n:root { --brand-sampled: ${hex}; }\n`;
  await writeFile(cssOut, css);
}

function rgbToHsl(r, g, b) {
  r /= 255; g /= 255; b /= 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b);
  const l = (max + min) / 2;
  if (max === min) return [0, 0, l];
  const d = max - min;
  const s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
  let h;
  if (max === r) h = ((g - b) / d + (g < b ? 6 : 0)) * 60;
  else if (max === g) h = ((b - r) / d + 2) * 60;
  else h = ((r - g) / d + 4) * 60;
  return [h, s, l];
}

const toHex = (n) => Math.round(n).toString(16).padStart(2, "0");

async function sampleGreen(sharp, buf) {
  const { data, info } = await sharp(buf)
    .resize(200, 200, { fit: "inside" })
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  // Bucket every saturated, green-hued pixel and take the most common bucket.
  const buckets = new Map();
  for (let i = 0; i < data.length; i += info.channels) {
    const [r, g, b, a] = [data[i], data[i + 1], data[i + 2], data[i + 3]];
    if (a < 200) continue;
    const [h, s, l] = rgbToHsl(r, g, b);
    if (h < 70 || h > 170 || s < 0.25 || l < 0.08 || l > 0.75) continue;
    const key = `${r >> 4}-${g >> 4}-${b >> 4}`;
    const entry = buckets.get(key) ?? { n: 0, r: 0, g: 0, b: 0 };
    entry.n++; entry.r += r; entry.g += g; entry.b += b;
    buckets.set(key, entry);
  }
  const best = [...buckets.values()].sort((a, b) => b.n - a.n)[0];
  if (!best || best.n < 20) return null;
  return `#${toHex(best.r / best.n)}${toHex(best.g / best.n)}${toHex(best.b / best.n)}`.toUpperCase();
}

async function main() {
  await mkdir(brandDir, { recursive: true });

  let buf;
  try {
    const res = await fetch(LOGO_URL, {
      signal: AbortSignal.timeout(15000),
      headers: { "User-Agent": "Mozilla/5.0 (compatible; ComprehensiveIrrigationSiteBuild/1.0)" },
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    buf = Buffer.from(await res.arrayBuffer());
    const isPng = buf.length > 8 && buf.subarray(0, 4).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47]));
    if (!isPng) throw new Error("response was not a PNG");
  } catch (err) {
    console.warn(`[fetch-logo] Could not download logo (${err.message}). Using runtime proxy + fallback green.`);
    if (!existsSync(cssOut)) await writeBrandCss(FALLBACK_GREEN, "fallback estimate");
    return;
  }

  await writeFile(path.join(brandDir, "logo.png"), buf);
  console.log(`[fetch-logo] Saved logo (${Math.round(buf.length / 1024)} KB).`);

  let sharp;
  try {
    sharp = (await import("sharp")).default;
  } catch {
    console.warn("[fetch-logo] sharp unavailable; skipping favicon sizes and colour sampling.");
    await writeBrandCss(FALLBACK_GREEN, "fallback estimate");
    return;
  }

  for (const size of [32, 180, 192, 512]) {
    await sharp(buf)
      .resize(size, size, { fit: "contain", background: { r: 255, g: 255, b: 255, alpha: 1 } })
      .png()
      .toFile(path.join(brandDir, `icon-${size}.png`));
  }

  const green = await sampleGreen(sharp, buf);
  await writeBrandCss(green ?? FALLBACK_GREEN, green ? "sampled from logo.png" : "fallback estimate");
  console.log(`[fetch-logo] Brand green: ${green ?? `${FALLBACK_GREEN} (fallback)`}`);
}

main().catch(async (err) => {
  console.warn(`[fetch-logo] Unexpected error: ${err.message}`);
  if (!existsSync(cssOut)) await writeBrandCss(FALLBACK_GREEN, "fallback estimate");
});
